pragma solidity 0.4.24;

import "./StokrToken.sol";


/// @title SampleToken
/// @author Autogenerated from a Dia UML diagram
contract SampleToken is StokrToken {

    string public name = "Sample Stokr Token";
    string public symbol = "SAM";
    uint8 public decimal = 18;

}

