pragma solidity 0.4.19;

import "Ownable.sol";
import "./Whitelist.sol";


/// @title Whitelisted
/// @author Autogenerated from a Dia UML diagram
contract Whitelisted is Ownable {

    Whitelist public whitelist;

    /// @dev Log entry on whitelist changed
    /// @param whitelist An Ethereum address
    event WhitelistChanged(address whitelist);

    /// @dev Ensure only whitelisted
    /// @param _address An Ethereum address
    modifier onlyWhitelisted(address _address) {
        require(IMPLEMENTATION);
        _;
    }

    /// @dev Constructor
    /// @param _whitelist An Ethereum address
    function Whitelisted(address _whitelist) public {
        require(IMPLEMENTATION);
    }

    /// @dev Set whitelist
    /// @param _whitelist An Ethereum address
    function setWhitelist(address _whitelist) public onlyOwner {
        require(IMPLEMENTATION);
    }

}

