pragma solidity 0.4.24;

import "./StokrToken.sol";


/// @title StokrToken
/// @author Autogenerated from a Dia UML diagram
contract SampleToken is StokrToken {

    string public name = "Sample Stokr Token";
    string public symbol = "SAM";
    uint8 public decimals = 18;

    constructor(
        string memory _name,
        string memory _symbol,
        Whitelist _whitelist,
        address _profitDepositor,
        address _keyRecoverer
    )
        public
        StokrToken(_whitelist, _profitDepositor, _keyRecoverer)
    {
        name = _name;
        symbol = _symbol;
    }

}
