pragma solidity 0.4.19;

import "./SicosToken.sol";


/// @title SicosToken
/// @author Autogenerated from a Dia UML diagram
contract SampleToken is SicosToken {

    string public name = "Sample Sicos Token";
    string public symbol = "SAM";
    uint public decimal = 18;

}
