pragma solidity ^0.4.20;

import "./HarvestToken.sol";

/// @title SicosToken
/// @author Autogenerated from a Dia UML diagram
contract SicosToken is HarvestToken {

    string public name;
    string public symbol;
    uint public decimal;

}
